version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: top
    # ports:
    #   - 0.0.0.0:2083:8080
    volumes:
      - './:/usr/src/app'
    tty: true
    stdin_open: true
    environment:
      TZ: Asia/Tokyo
      # PORT: 8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ utility, compute, video ]
